package com.example.count;

/**
 * Prints the number of 6's, 9's, consecutive 6's and consecutive 9's by passing a 
 * collection of random numbers generated by the RandomNumGenerator Class.
 * 
 * Namita Anand
 * 8 March 2017
 * CountingYour6sAnd9s Project
 */
import java.util.ArrayList;

public class MainController {

	public static void main(String[] args) {

		long start = System.currentTimeMillis();

		ArrayList<Integer> intList = new ArrayList<Integer>();
		intList = RandomNumGenerator.randomNumGenerator();

		int numOfSixes = Counter.countsSix(intList);
		System.out.println("Number of 6's in the list: " + numOfSixes);

		int numOfNines = Counter.countsNine(intList);
		System.out.println("Number of 9's in the list: " + numOfNines);

		int numOfConSixes = Counter.countsConsecutiveSixes(intList);
		System.out.println("Number of consecutive 6's in the list: " + numOfConSixes);

		int numOfConNines = Counter.countsConsecutiveNines(intList);
		System.out.println("Number of consecutive 9's in the list: " + numOfConNines);

		long stop = System.currentTimeMillis();

		long totalTime = stop - start;

		System.out.println("Total time taken: " + totalTime + "ms");

	}

}
